### ISSUE TITLE
actionrenderer Plugin + xbr plugin

### ISSUE THREAD

**Issue by apraadrienpro** [Chris--S/dokuwiki-plugin-xbr#2]
Hello,

I'm trying to get these two plugins (Xbr and actionrenderer) to work, but can't.
My steps : 
1. Install actionrenderer
2. Set renderer_xhtml parameter : "actionrenderer plugin"
3. Install Xbr.=> do not preserves line breaks
(4. Install autotooltip => this one is working.)

Is there a way to make them work together?

Thanks !

**Comment by Chris--S** [comment]
No, I don't think there is, only one renderer works at a time

Actionrenderer would need a plugin to handle its event when processing cdata.  The cdata handler (action plugin) would do the same as line #31 of https://github.com/Chris--S/dokuwiki-plugin-xbr/blob/7ab976f9cef474a690d00189b578377f47371207/renderer.php#L31

Chris

**Comment by apraadrienpro** [comment]
Woah. I did not expect an answer so quickly.
Thank you for this and for your plugin!
